(define (cubic a b c)
        (lambda (x) 
                (+ (cube x)
                (* a (square x))
                (* b x)
                c)))
(define (deriv g)
    (lambda (x) (/ (- (g (+ x dx)) (g x))
    dx)))
(define dx 0.00001)
(define (cube x)
    (* x x x))
(define (newton-transform g) 
    (lambda (x)
        (- x (/ (g x)((deriv g) x)))))
(define (newton-method g guess)
    (fixed-point (newton-transform g) guess))
(display (newton-method (cubic 1 2 3 ) 1))
(exit)