(define (function1 n)
        (cond ((= n 1) 1)
                ((= n 2) 2)
                ((or (= n 3) (> n 3)) (+ (function (- n 1)) (* 2 (function (- n 2))) (* 2 (function (- n 2)))))))
(define (function2 n)
        (cond ((= n 1) 1)
                ((= n 2) 2)
                (())))
(display (function1 6))
(exit)
(define (function2))