(define (deriv g)
    (lambda (x) (/ (- (g (+ x dx)) (g x))
    dx)))
(define dx 0.00001)
(define (cube x)
    (* x x x))
(define (new-ton transform)
    (lambda (x)
        (- x (/ (g x)((deriv g) x)))))
(define (newtons-method g guess)
    (fixed-point (newton-transform g) guess))
(display ((deriv cube) 5))
(exit)